import os
from datetime import timedelta

DEBUG = True
#session
SECRET_KEY = os.urandom(24)
#PERMANENT_SESSION_LIFETIME = timedelta(days=7)

#数据库，改成自己的
SQLALCHEMY_POOL_SIZE = 100
DIALECT = "mysql"
DRIVER = "pymysql"
USERNAME = "root"
PASSWORD = "111111"
HOST = "127.0.0.1"
RORT = "3310"
DATEBASE = "dataset"

SQLALCHEMY_TRACK_MODIFICATIONS = False
#SQLALCHEMY_COMMIT_TEARDOWN = True

SQLALCHEMY_DATABASE_URI = "{}+{}://{}:{}@{}:{}/{}?charset=utf8".format(DIALECT,DRIVER,USERNAME,PASSWORD,HOST,RORT,DATEBASE)

SQLALCHEMY_TRACK_MODIFICATIONS = False